name: Run Instagram Bot Daily

on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 12:00 UTC every day
  workflow_dispatch:      # Allows manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        python -m playwright install --with-deps chromium
    
    - name: Verify Playwright Installation
      run: playwright --version
    
    - name: Run bot
      env:
        INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
        INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
        TARGET_ACCOUNT: ${{ secrets.TARGET_ACCOUNT }}
      run: python main.py | tee bot_log.txt
    
    - name: Upload logs and screenshots
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: bot-artifacts
        path: |
          bot_log.txt
          error_*.png
          login_error_*.png
