name: Run Instagram Bot Daily

on:
  schedule:
    - cron: '12 * * *'  # Runs at 12:00 UTC every day
  workflow_dispatch:      # Allows manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        python -m playwright install --with-deps chromium
    
    - name: Run bot
      env:
        INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
        INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
        TARGET_ACCOUNT: ${{ secrets.TARGET_ACCOUNT }}
      run: python main.py
    
    - name: Upload screenshots
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: |
          error_*.png
          login_error_*.png
