name: floww
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential openjdk-11-jdk libssl-dev libffi-dev python3-dev
          pip install -r requirements.txt
      - name: Initialize Buildozer
        run: buildozer init
      - name: Build APK
        run: buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: floww-apk
          path: bin/
